import 'package:game_boy_graphics_editor/models/sourceConverters/source_parser.dart';

void main() {
  final parser = SourceParser();
  const String cSource = '''
#pragma bank 255

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(birabuto)

const palette_color_t birabuto_palettes[4] = {
	RGB8(255,255,255), RGB8(170,170,170), RGB8( 85, 85, 85), RGB8(  0,  0,  0)
	
};

const uint8_t birabuto_tiles[960] = {
	0xff,0x00,0xff,0x00,
	0xff,0x00,0xff,0x00,
	0xff,0x00,0xff,0x00
	};
''';

  // Parse all arrays
  final arrays = parser.parseAllArrays(cSource);

  print('Found ${arrays.length} integer arrays:');
  for (final array in arrays) {
    print(array);
    print(
      'First few values: ${array.data.take(10).map((v) => '0x${v.toRadixString(16).padLeft(2, '0')}').join(', ')}',
    );
    print('---');
  }

  // Example new values
  final newValues = [0x11, 0x22, 0x33, 0x44];

  //final updatedSource = updateArrayValues(cSource, arrays.first, newValues);
  //print(updatedSource);
}