#pragma bank {{bank}}

//AUTOGENERATED FILE FROM game_boy_graphics_editor

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF({{name}})

const unsigned char {{name}}_map[{{length}}] = {{{data}}};
