#pragma bank {{bank}}

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF({{name}})


const unsigned char {{name}}_map[{{length}}] = { {{data}} };
