//AUTOGENERATED FILE FROM game_boy_graphics_editor
#ifndef METASPRITE_{{name}}_H
#define METASPRITE_{{name}}_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define {{name}}_TILE_ORIGIN {{tile_origin}};
#define {{name}}_TILE_W 8
#define {{name}}_TILE_H 8
#define {{name}}_WIDTH {{width}};
#define {{name}}_HEIGHT {{height}};
#define {{name}}_TILE_COUNT 0
#define {{name}}_PALETTE_COUNT 1
#define {{name}}_COLORS_PER_PALETTE 4
#define {{name}}_TOTAL_COLORS 4
#define {{name}}_MAP_ATTRIBUTES 0
extern const unsigned char {{name}}_map[{{length}}];
#define {{name}}_map_attributes {{name}}_map

BANKREF_EXTERN({{name}})


#endif
