//AUTOGENERATED FILE FROM game_boy_graphics_editor
#ifndef METASPRITE_{{ name }}_H
#define METASPRITE_{{name}}_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define {{name}}_TILE_ORIGIN {{tile_origin}}
#define {{name}}_TILE_W 8
#define {{name}}_TILE_H 8
#define {{name}}_WIDTH {{width}}
#define {{name}}_HEIGHT {{height}}
#define {{name}}_TILE_COUNT {{tile_count}}
#define {{name}}_PALETTE_COUNT 1
#define {{name}}_COLORS_PER_PALETTE 4
#define {{name}}_TOTAL_COLORS 4

BANKREF_EXTERN({
{
name}})

extern const palette_color_t {
{
name}}_palettes[4];
extern const uint8_t {
{
name}}_tiles[{
{
length}}];

#endif
