 // AUTOGENERATED FILE FROM game_boy_graphics_editor
#ifndef MAP_number_map_H
#define MAP_number_map_H
#define number_map_TILE_ORIGIN 0
#define number_map_WIDTH 4
#define number_map_HEIGHT 4


extern const unsigned char number_map[];

#endif
