//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_numbers_transposed_H
#define METASPRITE_numbers_transposed_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define numbers_transposed_TILE_ORIGIN 0
#define numbers_transposed_TILE_W 8
#define numbers_transposed_TILE_H 8
#define numbers_transposed_WIDTH 32
#define numbers_transposed_HEIGHT 32
#define numbers_transposed_TILE_COUNT 16
#define numbers_transposed_PALETTE_COUNT 1
#define numbers_transposed_COLORS_PER_PALETTE 4
#define numbers_transposed_TOTAL_COLORS 4
#define numbers_transposed_MAP_ATTRIBUTES 0

BANKREF_EXTERN(numbers_transposed)

extern const palette_color_t numbers_transposed_palettes[4];
extern const uint8_t numbers_transposed_tiles[256];

extern const unsigned char numbers_transposed_map[16];
#define numbers_transposed_map_attributes numbers_transposed_map

#endif
