//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_number_map_H
#define METASPRITE_number_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define number_map_TILE_ORIGIN 0
#define number_map_TILE_W 8
#define number_map_TILE_H 8
#define number_map_WIDTH 32
#define number_map_HEIGHT 32
#define number_map_TILE_COUNT 16
#define number_map_PALETTE_COUNT 1
#define number_map_COLORS_PER_PALETTE 4
#define number_map_TOTAL_COLORS 4
#define number_map_MAP_ATTRIBUTES 0
extern const unsigned char number_map_map[16];
#define number_map_map_attributes number_map_map

BANKREF_EXTERN(number_map)

extern const palette_color_t number_map_palettes[4];
extern const uint8_t number_map_tiles[256];

#endif
