//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_numbers_H
#define METASPRITE_numbers_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define numbers_TILE_ORIGIN 0
#define numbers_TILE_W 8
#define numbers_TILE_H 8
#define numbers_WIDTH 32
#define numbers_HEIGHT 32
#define numbers_TILE_COUNT 16
#define numbers_PALETTE_COUNT 1
#define numbers_COLORS_PER_PALETTE 4
#define numbers_TOTAL_COLORS 4
#define numbers_MAP_ATTRIBUTES 0
extern const unsigned char numbers_map[16];
#define numbers_map_attributes numbers_map

BANKREF_EXTERN(numbers)

extern const palette_color_t numbers_palettes[4];
extern const uint8_t numbers_tiles[256];

#endif
