import 'package:game_boy_graphics_editor/models/graphics/background.dart';
import 'package:game_boy_graphics_editor/models/sourceConverters/source_converter.dart';

import '../graphics/graphics.dart';

class GBDKBackgroundConverter extends SourceConverter {
  static final GBDKBackgroundConverter _singleton =
      GBDKBackgroundConverter._internal();

  factory GBDKBackgroundConverter() {
    return _singleton;
  }

  GBDKBackgroundConverter._internal();

  @override
  String toHeader(Graphics graphics, String name) {
    Background background = graphics as Background;

    return """ // AUTOGENERATED FILE FROM game_boy_graphics_editor
#ifndef MAP_${name}_H
#define MAP_${name}_H
#define ${name}_TILE_ORIGIN ${background.tileOrigin}
#define ${name}_WIDTH ${graphics.width}
#define ${name}_HEIGHT ${graphics.height}


extern const unsigned char $name[];

#endif
""";
  }

  @override
  String toSource(Graphics graphics, String name) =>
      """const unsigned char $name[] = {${formatOutput(graphics.data.map((e) => decimalToHex(e, prefix: true)).toList())}};""";

  Background fromGraphics(Graphics graphics) => Background(
    data: graphics.data,
    width: graphics.width ~/ 8,
    height: graphics.height ~/ 8,
  );
}
