name: game_boy_graphics_editor
description: Edit GBDK graphics source files

version: 2.2.0+8

publish_to: 'none'

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^13.1.0
  image: ^4.10.1
  flutter_bloc: ^9.1.0
  replay_bloc: ^0.3.0
  two_dimensional_scrollables: ^0.5.5
  shared_preferences: ^2.5.5
  path: ^1.8.3
  http: ^1.6.0
  equatable: ^3.0.0
  petitparser: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

